name: InlineEditor
author: reednj
category: Widgets
tags: [ajax, element, interface]
docs: http://github.com/reednj/InlineEditor/blob/master/Docs/
demo: http://popacular.com/inline-editor/Test/demo.html
